from __future__ import annotations

DEFAULT_CONTACT_COUNTRY_CODE = "DE"

COUNTRY_OPTIONS: list[tuple[str, str]] = [
    ("AF", "Afghanistan"),
    ("EG", "Aegypten"),
    ("AX", "Alandinseln"),
    ("AL", "Albanien"),
    ("DZ", "Algerien"),
    ("AS", "Amerikanisch-Samoa"),
    ("VI", "Amerikanische Jungferninseln"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AI", "Anguilla"),
    ("AQ", "Antarktis"),
    ("AG", "Antigua und Barbuda"),
    ("GQ", "Aequatorialguinea"),
    ("AR", "Argentinien"),
    ("AM", "Armenien"),
    ("AW", "Aruba"),
    ("AZ", "Aserbaidschan"),
    ("ET", "Aethiopien"),
    ("AU", "Australien"),
    ("BS", "Bahamas"),
    ("BH", "Bahrain"),
    ("BD", "Bangladesch"),
    ("BB", "Barbados"),
    ("BE", "Belgien"),
    ("BZ", "Belize"),
    ("BJ", "Benin"),
    ("BM", "Bermuda"),
    ("BT", "Bhutan"),
    ("BO", "Bolivien"),
    ("BQ", "Bonaire, Sint Eustatius und Saba"),
    ("BA", "Bosnien und Herzegowina"),
    ("BW", "Botsuana"),
    ("BV", "Bouvetinsel"),
    ("BR", "Brasilien"),
    ("IO", "Britisches Territorium im Indischen Ozean"),
    ("VG", "Britische Jungferninseln"),
    ("BN", "Brunei"),
    ("BG", "Bulgarien"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CK", "Cookinseln"),
    ("CR", "Costa Rica"),
    ("CW", "Curaçao"),
    ("DK", "Daenemark"),
    ("DE", "Deutschland"),
    ("DM", "Dominica"),
    ("DO", "Dominikanische Republik"),
    ("DJ", "Dschibuti"),
    ("EC", "Ecuador"),
    ("SV", "El Salvador"),
    ("CI", "Elfenbeinkueste"),
    ("ER", "Eritrea"),
    ("EE", "Estland"),
    ("SZ", "Eswatini"),
    ("FK", "Falklandinseln"),
    ("FO", "Faeroeer"),
    ("FJ", "Fidschi"),
    ("FI", "Finnland"),
    ("FR", "Frankreich"),
    ("GF", "Franzoesisch-Guayana"),
    ("PF", "Franzoesisch-Polynesien"),
    ("TF", "Franzoesische Sued- und Antarktisgebiete"),
    ("GA", "Gabun"),
    ("GM", "Gambia"),
    ("GE", "Georgien"),
    ("GH", "Ghana"),
    ("GI", "Gibraltar"),
    ("GD", "Grenada"),
    ("GR", "Griechenland"),
    ("GL", "Groenland"),
    ("GP", "Guadeloupe"),
    ("GU", "Guam"),
    ("GT", "Guatemala"),
    ("GG", "Guernsey"),
    ("GN", "Guinea"),
    ("GW", "Guinea-Bissau"),
    ("GY", "Guyana"),
    ("HT", "Haiti"),
    ("HM", "Heard und McDonaldinseln"),
    ("HN", "Honduras"),
    ("HK", "Hongkong"),
    ("IN", "Indien"),
    ("ID", "Indonesien"),
    ("IQ", "Irak"),
    ("IR", "Iran"),
    ("IE", "Irland"),
    ("IS", "Island"),
    ("IM", "Isle of Man"),
    ("IL", "Israel"),
    ("IT", "Italien"),
    ("JM", "Jamaika"),
    ("JP", "Japan"),
    ("YE", "Jemen"),
    ("JE", "Jersey"),
    ("JO", "Jordanien"),
    ("KY", "Kaimaninseln"),
    ("KH", "Kambodscha"),
    ("CM", "Kamerun"),
    ("CA", "Kanada"),
    ("CV", "Kap Verde"),
    ("KZ", "Kasachstan"),
    ("QA", "Katar"),
    ("KE", "Kenia"),
    ("KG", "Kirgisistan"),
    ("KI", "Kiribati"),
    ("CC", "Kokosinseln"),
    ("CO", "Kolumbien"),
    ("KM", "Komoren"),
    ("CG", "Kongo"),
    ("CD", "Kongo, Demokratische Republik"),
    ("KP", "Korea, Demokratische Volksrepublik"),
    ("KR", "Korea, Republik"),
    ("HR", "Kroatien"),
    ("CU", "Kuba"),
    ("KW", "Kuwait"),
    ("LA", "Laos"),
    ("LS", "Lesotho"),
    ("LV", "Lettland"),
    ("LB", "Libanon"),
    ("LR", "Liberia"),
    ("LY", "Libyen"),
    ("LI", "Liechtenstein"),
    ("LT", "Litauen"),
    ("LU", "Luxemburg"),
    ("MO", "Macau"),
    ("MG", "Madagaskar"),
    ("MW", "Malawi"),
    ("MY", "Malaysia"),
    ("MV", "Malediven"),
    ("ML", "Mali"),
    ("MT", "Malta"),
    ("MA", "Marokko"),
    ("MH", "Marshallinseln"),
    ("MQ", "Martinique"),
    ("MR", "Mauretanien"),
    ("MU", "Mauritius"),
    ("YT", "Mayotte"),
    ("MX", "Mexiko"),
    ("FM", "Mikronesien"),
    ("MD", "Moldau"),
    ("MC", "Monaco"),
    ("MN", "Mongolei"),
    ("ME", "Montenegro"),
    ("MS", "Montserrat"),
    ("MZ", "Mosambik"),
    ("MM", "Myanmar"),
    ("NA", "Namibia"),
    ("NR", "Nauru"),
    ("NP", "Nepal"),
    ("NC", "Neukaledonien"),
    ("NZ", "Neuseeland"),
    ("NI", "Nicaragua"),
    ("NL", "Niederlande"),
    ("NE", "Niger"),
    ("NG", "Nigeria"),
    ("NU", "Niue"),
    ("MK", "Nordmazedonien"),
    ("MP", "Nordoestliche Marianen"),
    ("NF", "Norfolkinsel"),
    ("NO", "Norwegen"),
    ("OM", "Oman"),
    ("AT", "Oesterreich"),
    ("TL", "Osttimor"),
    ("PK", "Pakistan"),
    ("PS", "Palaestinensische Gebiete"),
    ("PW", "Palau"),
    ("PA", "Panama"),
    ("PG", "Papua-Neuguinea"),
    ("PY", "Paraguay"),
    ("PE", "Peru"),
    ("PH", "Philippinen"),
    ("PN", "Pitcairninseln"),
    ("PL", "Polen"),
    ("PT", "Portugal"),
    ("PR", "Puerto Rico"),
    ("RE", "Reunion"),
    ("RW", "Ruanda"),
    ("RO", "Rumänien"),
    ("RU", "Russland"),
    ("SB", "Salomonen"),
    ("ZM", "Sambia"),
    ("WS", "Samoa"),
    ("SM", "San Marino"),
    ("ST", "Sao Tome und Principe"),
    ("SA", "Saudi-Arabien"),
    ("SE", "Schweden"),
    ("CH", "Schweiz"),
    ("SN", "Senegal"),
    ("RS", "Serbien"),
    ("SC", "Seychellen"),
    ("SL", "Sierra Leone"),
    ("ZW", "Simbabwe"),
    ("SG", "Singapur"),
    ("SX", "Sint Maarten"),
    ("SK", "Slowakei"),
    ("SI", "Slowenien"),
    ("SO", "Somalia"),
    ("ES", "Spanien"),
    ("LK", "Sri Lanka"),
    ("BL", "St. Barthelemy"),
    ("SH", "St. Helena, Ascension und Tristan da Cunha"),
    ("KN", "St. Kitts und Nevis"),
    ("LC", "St. Lucia"),
    ("MF", "St. Martin"),
    ("PM", "St. Pierre und Miquelon"),
    ("VC", "St. Vincent und die Grenadinen"),
    ("ZA", "Suedafrika"),
    ("SD", "Sudan"),
    ("GS", "Suedgeorgien und die Suedlichen Sandwichinseln"),
    ("SS", "Suedsudan"),
    ("SR", "Suriname"),
    ("SJ", "Svalbard und Jan Mayen"),
    ("SY", "Syrien"),
    ("TJ", "Tadschikistan"),
    ("TW", "Taiwan"),
    ("TZ", "Tansania"),
    ("TH", "Thailand"),
    ("TG", "Togo"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TT", "Trinidad und Tobago"),
    ("TD", "Tschad"),
    ("CZ", "Tschechien"),
    ("TN", "Tunesien"),
    ("TR", "Tuerkei"),
    ("TM", "Turkmenistan"),
    ("TC", "Turks- und Caicosinseln"),
    ("TV", "Tuvalu"),
    ("UG", "Uganda"),
    ("UA", "Ukraine"),
    ("HU", "Ungarn"),
    ("UY", "Uruguay"),
    ("UZ", "Usbekistan"),
    ("VU", "Vanuatu"),
    ("VA", "Vatikanstadt"),
    ("VE", "Venezuela"),
    ("AE", "Vereinigte Arabische Emirate"),
    ("US", "Vereinigte Staaten"),
    ("GB", "Vereinigtes Koenigreich"),
    ("VN", "Vietnam"),
    ("WF", "Wallis und Futuna"),
    ("CX", "Weihnachtsinsel"),
    ("EH", "Westsahara"),
    ("BY", "Weissrussland"),
    ("CF", "Zentralafrikanische Republik"),
    ("CY", "Zypern"),
]

COUNTRY_LABEL_BY_CODE: dict[str, str] = dict(COUNTRY_OPTIONS)
COUNTRY_OPTION_MAP: dict[str, str] = dict(COUNTRY_OPTIONS)
